// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace StockSense
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"ProductID")]
            public string ProductID { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"ProductName")]
            public string ProductName { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Brand")]
            public string Brand { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Category")]
            public string Category { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"QtySold")]
            public float QtySold { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"MonthNum")]
            public float MonthNum { get; set; }
            public float Year { get; internal set; }
        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"ProductID")]
            public float[] ProductID { get; set; }

            [ColumnName(@"ProductName")]
            public float[] ProductName { get; set; }

            [ColumnName(@"Brand")]
            public float[] Brand { get; set; }

            [ColumnName(@"Category")]
            public float[] Category { get; set; }

            [ColumnName(@"QtySold")]
            public float QtySold { get; set; }

            [ColumnName(@"MonthNum")]
            public float MonthNum { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.Combine(AppContext.BaseDirectory, "MLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
