// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;

namespace StockSense
{
    public partial class MLModel
    {
        public static void Train(string outputModelPath, IEnumerable<ModelInput> trainingData)
        {
            var mlContext = new MLContext();
            var data = mlContext.Data.LoadFromEnumerable<ModelInput>(trainingData);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            DataViewSchema dataViewSchema = data.Schema;
            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }

        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);
            return model;
        }

        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Invalid tags removed from here
            var pipeline = mlContext.Transforms.ReplaceMissingValues(@"MonthNum", @"MonthNum")
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName: @"ProductID", outputColumnName: @"ProductID"))
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName: @"ProductName", outputColumnName: @"ProductName"))
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName: @"Brand", outputColumnName: @"Brand"))
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName: @"Category", outputColumnName: @"Category"))
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new[] { @"MonthNum", @"ProductID", @"ProductName", @"Brand", @"Category" }))
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options()
                                    {
                                        NumberOfLeaves = 885,
                                        NumberOfIterations = 4,
                                        MinimumExampleCountPerLeaf = 20,
                                        LearningRate = 0.9999997766729865,
                                        LabelColumnName = @"QtySold",
                                        FeatureColumnName = @"Features",
                                        Booster = new GradientBooster.Options()
                                        {
                                            SubsampleFraction = 0.2685315600597058,
                                            FeatureFraction = 0.9767894145782053,
                                            L1Regularization = 2E-10,
                                            L2Regularization = 0.9999997766729865
                                        },
                                        MaximumBinCountPerFeature = 210
                                    }));

            return pipeline;
        }
    }
}