using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using StockSense.Application.DTOs;
using StockSense.Application.Interfaces;

namespace StockSense.Infrastructure.Services;

public class DocumentService : IDocumentService
{
    public byte[] GenerateOrderSlipPdf(OrderSlipDto slipDto)
    {
        // Note: For production, it's best practice to move this license setup 
        // to your Web project's Program.cs, but it works fine here for now.
        QuestPDF.Settings.License = LicenseType.Community;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(1, Unit.Inch);
                
                page.Header()
                    .Text($"Order Slip: {slipDto.SlipNumber}")
                    .FontSize(20)
                    .SemiBold()
                    .FontColor(Colors.Blue.Medium);

                page.Content().Column(col =>
                {
                    col.Item().Text($"Supplier: {slipDto.SupplierName}");
                    col.Item().Text($"Date: {slipDto.DateGenerated:MM/dd/yyyy}");
                    
                    col.Item().PaddingTop(10).Table(table =>
                    {
                        table.ColumnsDefinition(columns => {
                            columns.RelativeColumn(3); // Product Name column gets 75% width
                            columns.RelativeColumn(1); // Quantity column gets 25% width
                        });
                        
                        table.Header(header => {
                            header.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingBottom(5).Text("Product").SemiBold();
                            header.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingBottom(5).Text("Quantity").SemiBold();
                        });
                        
                        foreach (var item in slipDto.Items)
                        {
                            table.Cell().PaddingVertical(2).Text($"{item.ProductName} ({item.Brand})");
                            table.Cell().PaddingVertical(2).Text(item.Quantity.ToString());
                        }
                    });
                });
                
                page.Footer()
                    .AlignCenter()
                    .Text(x => {
                        x.Span("Generated by StockSense Inventory System - Page ");
                        x.CurrentPageNumber();
                    });
            });
        }).GeneratePdf();
    }
}